apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  labels:
    app: myapplication
data:
  dbuser: root
  dburl: jdbc:mysql://mycluster:3306/BankDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC