version: '3.8'
services:
    mysql:
      image: mysql
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: Test@123
        MYSQL_DATABASE: BankDB
      healthcheck:  
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pTest@123"]
        interval: 10s
        start_interval: 100s
        timeout: 10s
      restart: always
      ports:
        - 3306:3306
      networks:
        - bank-app-network
      volumes:
        - mysql-bank-app-vol:/var/lib/mysql
    
    bankapp:
      image: joakim077/spring-boot-bankapp:v1
      container_name: bankapp
      environment:
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/BankDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        SPRING_DATASOURCE_PASSWORD: Test@123
      healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health"]
        interval: 10s
        timeout: 10s
        start_interval: 60s
      restart: always
      depends_on:
        - mysql
      ports:
        - 8080:8080
      networks:
        - bank-app-network

networks:
  bank-app-network:

volumes:
  mysql-bank-app-vol:
      